; Load Xdebug extension
zend_extension=xdebug

; Enable debug mode
xdebug.mode = debug
; Start Xdebug with each request
xdebug.start_with_request = yes
; Set the client host
xdebug.client_host=host.docker.internal
; Set the client port
xdebug.client_port=9003
